### ISSUE TITLE
Mod Buttons doesn't render at the right place when Quit button is enabled.

### ISSUE THREAD

**Issue by thecatcore** [calmilamsy/ModMenu#2]
![image](https://user-images.githubusercontent.com/34719527/174850211-5ac36622-c674-498a-95ae-0ed4b68d28ae.png)

**Comment by thecatcore** [comment]
and Options button is renamed to Texture Packs lol

**Comment by fineless71** [comment]
I used release v1.8.5-beta.3 and it worked fine for me:
![image](https://github.com/calmilamsy/ModMenu/assets/118756680/1d0ea58e-3bfd-4f51-a850-cd8dba2b282b)

**Edit:** Worked fine on Babric, but not Cursed Fabric, weird...
